# Generated by Django 4.0.4 on 2022-06-27 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilCoordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=70, null=True)),
                ('email', models.EmailField(max_length=70, null=True)),
                ('telefone', models.CharField(max_length=12, null=True)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.curso')),
                ('usuario_coordenador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150, null=True)),
                ('cargo_atual', models.CharField(max_length=50, null=True)),
                ('foto', models.CharField(max_length=150, null=True)),
                ('empresa_atual', models.CharField(max_length=50, null=True)),
                ('trabalha_area', models.CharField(choices=[('Sim', 'Sim'), ('Nao', 'Não'), ('EmParte', 'Em parte')], max_length=8, null=True)),
                ('ifb_ajudou', models.CharField(choices=[('Sim', 'Sim'), ('Nao', 'Não'), ('EmParte', 'Em parte')], max_length=8, null=True)),
                ('grade_ifb', models.CharField(max_length=10, null=True)),
                ('curso_extra', models.CharField(choices=[('Sim', 'Sim'), ('Nao', 'Não')], max_length=10, null=True)),
                ('qual_curso_extra', models.CharField(max_length=30, null=True)),
                ('opiniao_curso_ifb', models.CharField(max_length=100, null=True)),
                ('pode_melhorar', models.CharField(max_length=100, null=True)),
                ('rede_social', models.CharField(max_length=100, null=True)),
                ('lattes', models.CharField(max_length=100, null=True)),
                ('validado', models.CharField(choices=[('Sim', 'Sim'), ('Nao', 'Não')], max_length=5, null=True)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.curso')),
                ('turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.turma')),
                ('usuario_aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
